# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lukgla/Desktop/Vivado/Lab5a/Lab5a.srcs/sources_1/ip/fifo_mem/fifo_mem.xci
# IP: The module: 'fifo_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lukgla/Desktop/Vivado/Lab5a/Lab5a.gen/sources_1/ip/fifo_mem/fifo_mem.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lukgla/Desktop/Vivado/Lab5a/Lab5a.gen/sources_1/ip/fifo_mem/fifo_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/lukgla/Desktop/Vivado/Lab5a/Lab5a.srcs/sources_1/ip/fifo_mem/fifo_mem.xci
# IP: The module: 'fifo_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lukgla/Desktop/Vivado/Lab5a/Lab5a.gen/sources_1/ip/fifo_mem/fifo_mem.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lukgla/Desktop/Vivado/Lab5a/Lab5a.gen/sources_1/ip/fifo_mem/fifo_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
